<h2 style="color:green" align="center"> Machine Learning With Python: Linear Regression Multiple Variables</h2>

<h3 style="color:purple">Sample problem of predicting home price in monroe, new jersey (USA)</h3>

Below is the table containing home prices in monroe twp, NJ. Here price depends on **area (square feet), bed rooms and age of the home (in years)**. Given these prices we have to predict prices of new homes based on area, bed rooms and age.

<img src="homeprices.jpg" style='height:200px;width:350px'>

Given these home prices find out price of a home that has,

**3000 sqr ft area, 3 bedrooms, 40 year old**

**2500 sqr ft area, 4 bedrooms,  5 year old**

We will use regression with multiple variables here. Price can be calculated using following equation,

<img src="equation.jpg" >

Here area, bedrooms, age are called independant variables or **features** whereas price is a dependant variable

In [44]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [45]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

**Data Preprocessing: Fill NA values with median value of a column**

In [46]:
import math
med_bedrooms = math.floor(df.bedrooms.median())

In [47]:
df.bedrooms = df.bedrooms.fillna(med_bedrooms)

In [48]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [49]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [50]:
reg.coef_

array([   112.06244194,  23388.88007794,  -3231.71790863])

In [51]:
reg.intercept_

221323.00186540384

**Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old**

In [52]:
reg.predict([[3000, 3, 40]])

array([ 498408.25158031])

In [55]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540384

498408.25157402386

**Find price of home with 2500 sqr ft area, 4 bedrooms,  5 year old**

In [54]:
reg.predict([[2500, 4, 5]])

array([ 578876.03748933])

In [15]:
new_list=[]
words= ['darn', 'drat', 'fiddlesticks', 'fudge', 'geez', 'gosh', 'heck', 'shoot']
y= ['the', 'heck']
z= set(words) & set(y)
print(z)


{'heck'}


In [1]:
from jinja2 import Template
template = Template("Hello {{name}}!")
template.render(name='John Doe')

'Hello John Doe!'

In [19]:
x=2
y=3
print(f"x+y={x+y}")
print(f"x/y= {x/y:.60f}")

x+y=5
x/y= 0.666666666666666629659232512494781985878944396972656250000000


<h3>Exercise<h3>

In exercise folder (same level as this notebook on github) there is **hiring.csv**. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,


**2 yr experience, 9 test score, 6 interview score**

**12 yr experience, 10 test score, 10 interview score**


<h3>Answer<h3>

53713.86 and 93747.79

In [37]:
import sys
i =sys.maxsize
print(i)

9223372036854775807


In [40]:
i = i+sys.maxsize

In [41]:
print(i)

27670116110564327421


In [ ]:
18446744073709551715

In [54]:
f= sys.float_info.max
print(f)

1.7976931348623157e+308


In [55]:
print(f== f+1)


True


In [56]:
f+=1
print(f)

1.7976931348623157e+308


In [59]:
"x".join(["a","b","c"])

'axbxc'

In [65]:
def convert(string):
    l= list(string.split(" "))
    return l

str1 = "Mannawar is happy"
print(convert(str1))

['Mannawar', 'is', 'happy']


In [1]:
def world():
    print("Hello world")

In [3]:
import os

In [5]:
from flask import Flask, flash, jsonify, redirect, render_template, request, session
#from flask_session import Session
from tempfile import mkdtemp
from werkzeug.exceptions import default_exceptions, HTTPException, InternalServerError
from werkzeug.security import check_password_hash, generate_password_hash

In [3]:
def a(): return 10
type(a)
5//2
a={1:9, 2:8, 3:7}
a.items()

dict_items([(1, 9), (2, 8), (3, 7)])

In [15]:
class test():
    id=0
    def __init__(self, id):
        self.id= id
        id=2


In [17]:
        t=test(1)
        t.id

1

In [18]:
m=re.search(r'(ab[cd]?)', """"acdeabdabcde""")
m.groups()

NameError: name 're' is not defined