In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [6]:
df = pd.read_csv("c:\\Users\\Mannawar Hussain\\Desktop\\Machine learning\\ML\\2_linear_reg_multivariate\\homeprices.csv")

In [7]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [8]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [11]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [12]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [14]:
reg = linear_model.LinearRegression()
reg.fit(df[["area", "bedrooms", "age"]], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [15]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [16]:
reg.intercept_

221323.00186540408

In [20]:
reg.predict([[3000, 3, 10]])

array([595359.7888393])

In [21]:
 112.06244194*3000+23388.88007794*3 + -3231.71790863*10 +221323.00186540408

595359.7888329241

In [22]:
reg.predict([[2500, 4, 5]])

array([578876.03748933])

In [24]:
pip install word2number


The following command must be run outside of the IPython shell:

    $ pip install word2number

The Python package manager (pip) can only be used from outside of IPython.
Please reissue the `pip` command in a separate terminal or command prompt.

See the Python documentation for more information on how to install packages:

    https://docs.python.org/3/installing/


In [25]:
#exercise hiring
df1 = pd.read_csv("c:\\Users\\Mannawar Hussain\\Desktop\\Machine learning\\ML\\2_linear_reg_multivariate\\Exercise\\hiring.csv")

In [26]:
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [40]:
experience = {'five': 5, 'two': 2, 'seven': 7, 'three': 3, 'ten': 10, 'eleven': 11}
df1.experience = [experience[item] for item in df1.experience]
print (df1)


KeyError: 10

In [39]:
experience = {'five': 5, 'two': 2, 'seven': 7, 'three': 3, 'ten': 10, 'eleven': 11}
df1.experience = [experience[item] for item in df1.experience]
print (df1)

KeyError: 10

In [43]:
!pip install num2words

  Running setup.py bdist_wheel for docopt: started
  Running setup.py bdist_wheel for docopt: finished with status 'done'
  Stored in directory: C:\Users\Mannawar Hussain\AppData\Local\pip\Cache\wheels\9b\04\dd\7daf4150b6d9b12949298737de9431a324d4b797ffd63f526e
Successfully built docopt


In [44]:
!pip install word2number

  Running setup.py bdist_wheel for word2number: started
  Running setup.py bdist_wheel for word2number: finished with status 'done'
  Stored in directory: C:\Users\Mannawar Hussain\AppData\Local\pip\Cache\wheels\46\2f\53\5f5c1d275492f2fce1cdab9a9bb12d49286dead829a4078e0e
Successfully built word2number


In [45]:
from word2number import w2n