In [4]:
import numpy as np
a = np.arange (12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
for row in a:
    for cell in row:
        print (cell)


0
1
2
3
4
5
6
7
8
9
10
11


In [11]:
for row in a:
    print (row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [12]:
for cell in a.flatten():
    print (cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [18]:
for x in np.nditer(a, order = 'C'):
    print (x)

0
1
2
3
4
5
6
7
8
9
10
11


In [19]:
for x in np.nditer(a, order = 'F'):
    print (x)

0
4
8
1
5
9
2
6
10
3
7
11


In [28]:
for x in np.nditer(a, op_flags=['readwrite']):
 x[...]= x*x

In [23]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [30]:
b = np.arange(3,15,5).reshape(3,1)
b

array([[ 3],
       [ 8],
       [13]])

In [31]:
for x,y in np.nditer ([a,b]):
    print (x,y)

0 3
1 3
16 3
81 3
256 8
625 8
1296 8
2401 8
4096 13
6561 13
10000 13
14641 13
