In [1]:
import numpy as np 
import pandas as pd
from sklearn import datasets, linear_model

In [3]:
df = pd.read_csv("c:\\Users\\Mannawar Hussain\\Desktop\\homeprice in qatar.csv")
df

town  area   price
0   algharafa  2600  550000
1   algharafa  3000  565000
2   algharafa  3200  610000
3   algharafa  3600  680000
4   algharafa  4000  725000
5      alkhor  2600  585000
6      alkhor  2800  615000
7      alkhor  3300  650000
8      alkhor  3600  710000
9    alrayyan  2600  575000
10   alrayyan  2900  600000
11   alrayyan  3100  620000
12   alrayyan  3600  695000

In [4]:
df.head()

town  area   price
0  algharafa  2600  550000
1  algharafa  3000  565000
2  algharafa  3200  610000
3  algharafa  3600  680000
4  algharafa  4000  725000

In [5]:
model = linear_model.LinearRegression()

In [6]:
model.fit(df[['area']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [7]:
model.coef_

array([118.29495955])

In [8]:
model.intercept_

257056.627255756

In [10]:
model.predict([[5000]])

array([848531.42501556])

In [11]:
model.predict([[10000]])

array([1440006.22277536])

In [16]:
model.score


<bound method RegressorMixin.score of LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)>

In [17]:
import pickle # pickle module allows us to serialize python object into a file

In [18]:
with open ('model_pickle', 'wb') as f: # write mode in binary, file. model_pickle file is created see attached
    pickle.dump(model, f)

In [21]:
with open ('model_pickle', 'rb') as f: # read mode in binary
    mp = pickle.load (f)

In [23]:
mp.predict([[5000]]) # we can check that it predicted the pretty same output as was done by above model. So we can use this model to predict the home prices in Qatar

array([848531.42501556])

In [24]:
# now i want to use joblib from sklearn which is essentially used when there is large numpy arrays
from sklearn.externals import joblib

In [25]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [27]:
mj = joblib.load ('model_joblib')

In [28]:
mj.predict([[5000]]) # here we can see again prediction is essentially the same

array([848531.42501556])

In [29]:
mj.coef_

array([118.29495955])

In [30]:
mj.intercept_

257056.627255756