In [1]:
import pandas 
pandas.__version__

'0.23.4'

In [2]:
import numpy
numpy.__version__

'1.15.4'

In [3]:
import pandas as pd

In [4]:
data = pd.Series ([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [5]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [6]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
data [1]

0.5

In [8]:
data [1:3]

1    0.50
2    0.75
dtype: float64

In [9]:
data = pd.Series ([0.25, 0.5, 0.75, 1.0],
                 index =['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [10]:
data ['b']

0.5

In [11]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                index = ['2', '3', '4', '5'])
data


2    0.25
3    0.50
4    0.75
5    1.00
dtype: float64

In [12]:
population_dict = {"california": 38332521,
                  "Texas": 26448193,
                  "New york": 19651127,
                  "Florida":19552860,
                  "Illinois": 12882135}
population = pd.Series(population_dict)
population

california    38332521
Texas         26448193
New york      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [13]:
population ['california': 'New york']

california    38332521
Texas         26448193
New york      19651127
dtype: int64

In [14]:
pd.Series([2, 4, 6]) # in output first row is index starting with 0

0    2
1    4
2    6
dtype: int64

In [15]:
pd.Series (5, index = [100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [16]:
pd.Series({2:'a', 3:'b', 1:'c'})

2    a
3    b
1    c
dtype: object

In [17]:
# as generalized numpy array
area_dict = {'california': 423967, 'Texas': 695662, 'New York': 141927, 'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

california    423967
Texas         695662
New York      141927
Florida       170312
Illinois      149995
dtype: int64

In [18]:
states = pd.DataFrame({'population': population, 
                       'area': area})
states

population      area
Florida     19552860.0  170312.0
Illinois    12882135.0  149995.0
New York           NaN  141927.0
New york    19651127.0       NaN
Texas       26448193.0  695662.0
california  38332521.0  423967.0

In [19]:
states.index

Index(['Florida', 'Illinois', 'New York', 'New york', 'Texas', 'california'], dtype='object')

In [20]:
states.columns

Index(['population', 'area'], dtype='object')

In [21]:
states ['area']

Florida       170312.0
Illinois      149995.0
New York      141927.0
New york           NaN
Texas         695662.0
california    423967.0
Name: area, dtype: float64

In [22]:
pd.DataFrame

pandas.core.frame.DataFrame

In [23]:
pd.DataFrame(population, columns = ['population'])

population
california    38332521
Texas         26448193
New york      19651127
Florida       19552860
Illinois      12882135

In [24]:
data = [{'a': i, 'b': 2 * i}
       for i in range (3)]
pd.DataFrame (data)

a  b
0  0  0
1  1  2
2  2  4

In [27]:
pd.DataFrame({'poulation': population, 'area': area})

poulation      area
Florida     19552860.0  170312.0
Illinois    12882135.0  149995.0
New York           NaN  141927.0
New york    19651127.0       NaN
Texas       26448193.0  695662.0
california  38332521.0  423967.0

In [29]:
import numpy as np
pd.DataFrame(np.random.rand(3,2),
            columns = ['foo', 'bar'],
            index= ['a', 'b', 'c'])

foo       bar
a  0.512940  0.778259
b  0.752005  0.609068
c  0.405986  0.828239

In [35]:
A = np.zeros(3, dtype= [('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [36]:
pd.DataFrame (A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

In [40]:
ind = pd.Index ([2, 3, 5, 7, 9])
ind

Int64Index([2, 3, 5, 7, 9], dtype='int64')

In [41]:
ind [::2]

Int64Index([2, 5, 9], dtype='int64')

In [44]:
ind [::3]

Int64Index([2, 7], dtype='int64')

In [45]:
ind [::1]

Int64Index([2, 3, 5, 7, 9], dtype='int64')

In [46]:
ind.ndim

1

In [47]:
ind.shape

(5,)

In [48]:
ind.size

5

In [49]:
ind.dtype

dtype('int64')

In [50]:
print (ind.shape, ind.size, ind.ndim, ind.dtype)

(5,) 5 1 int64


In [55]:
ind [1] =[0]

TypeError: Index does not support mutable operations

In [56]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [57]:
indA.union(indB)

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [60]:
indA.symmetric_difference (indB)

Int64Index([1, 2, 9, 11], dtype='int64')

In [61]:
indA ^ indB

Int64Index([1, 2, 9, 11], dtype='int64')

In [62]:
data = pd.Series([.25, .5, .75, 1], index = ['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [65]:
data ['c']

0.75

In [66]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [67]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [70]:
data ['e']=1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [71]:
data [0:2]

a    0.25
b    0.50
dtype: float64

In [74]:
data [(data < 0.8) & (data >.25)] # masking

b    0.50
c    0.75
dtype: float64

In [75]:
data [['a', 'e']]  #fancy indexing

a    0.25
e    1.25
dtype: float64

In [77]:
data = pd.Series(['a', 'b', 'c'], index= [1, 2, 3])
data

1    a
2    b
3    c
dtype: object

In [78]:
data[1:3]

2    b
3    c
dtype: object

In [79]:
data.iloc[1:3]

2    b
3    c
dtype: object

In [80]:
data.loc[1:3]

1    a
2    b
3    c
dtype: object

In [82]:
area = pd.Series({'california': 425679, 'Texas': 654321, 'New york': 436369, 'Florida': 543156, 'Illinois': 765123})
pop = pd.Series({'california': 32425679, 'Texas': 43654321, 'New york': 56436369, 'Florida': 76543156, 'Illinois': 32765123})
data = pd.DataFrame({'area': area, 'pop': pop})
data

area       pop
california  425679  32425679
Texas       654321  43654321
New york    436369  56436369
Florida     543156  76543156
Illinois    765123  32765123

In [87]:
data.pop is data ['pop']

False

In [88]:
data['density']= data['pop']/data['area']
data

area       pop     density
california  425679  32425679   76.174016
Texas       654321  43654321   66.716980
New york    436369  56436369  129.331756
Florida     543156  76543156  140.922969
Illinois    765123  32765123   42.823341

In [89]:
data.values

array([[4.25679000e+05, 3.24256790e+07, 7.61740161e+01],
       [6.54321000e+05, 4.36543210e+07, 6.67169799e+01],
       [4.36369000e+05, 5.64363690e+07, 1.29331756e+02],
       [5.43156000e+05, 7.65431560e+07, 1.40922969e+02],
       [7.65123000e+05, 3.27651230e+07, 4.28233408e+01]])

In [90]:
data.T

california         Texas      New york       Florida      Illinois
area     4.256790e+05  6.543210e+05  4.363690e+05  5.431560e+05  7.651230e+05
pop      3.242568e+07  4.365432e+07  5.643637e+07  7.654316e+07  3.276512e+07
density  7.617402e+01  6.671698e+01  1.293318e+02  1.409230e+02  4.282334e+01

In [91]:
data.values [1]

array([6.54321000e+05, 4.36543210e+07, 6.67169799e+01])

In [92]:
data['area']

california    425679
Texas         654321
New york      436369
Florida       543156
Illinois      765123
Name: area, dtype: int64

In [93]:
data.iloc [:3, :2]

area       pop
california  425679  32425679
Texas       654321  43654321
New york    436369  56436369

In [98]:
data.loc[:'Illinois', :'pop']

area       pop
california  425679  32425679
Texas       654321  43654321
New york    436369  56436369
Florida     543156  76543156
Illinois    765123  32765123

In [107]:
data.loc[data.density>100, ['pop', 'density']]

pop     density
New york  56436369  129.331756
Florida   76543156  140.922969

In [101]:
data

area       pop     density
california  425679  32425679   76.174016
Texas       654321  43654321   66.716980
New york    436369  56436369  129.331756
Florida     543156  76543156  140.922969
Illinois    765123  32765123   42.823341

In [103]:
data.iloc[0,2]= 90
data

area       pop     density
california  425679  32425679   90.000000
Texas       654321  43654321   66.716980
New york    436369  56436369  129.331756
Florida     543156  76543156  140.922969
Illinois    765123  32765123   42.823341

In [108]:
data ['Florida' : 'Illinois']

area       pop     density
Florida   543156  76543156  140.922969
Illinois  765123  32765123   42.823341

In [112]:
data.loc ['california':'Florida']

area       pop     density
california  425679  32425679   90.000000
Texas       654321  43654321   66.716980
New york    436369  56436369  129.331756
Florida     543156  76543156  140.922969

In [113]:
data

area       pop     density
california  425679  32425679   90.000000
Texas       654321  43654321   66.716980
New york    436369  56436369  129.331756
Florida     543156  76543156  140.922969
Illinois    765123  32765123   42.823341

In [114]:
data[data.density < 100]

area       pop    density
california  425679  32425679  90.000000
Texas       654321  43654321  66.716980
Illinois    765123  32765123  42.823341