In [1]:
import numpy
numpy._version_


AttributeError: module 'numpy' has no attribute '_version_'

In [3]:
import numpy
numpy:version.version
    

NameError: name 'version' is not defined

In [4]:
import numpy as np


In [6]:
np?


In [2]:
result = 0
for i in range(100):
    result += i


In [4]:
for i in range(5)
print(i)

SyntaxError: invalid syntax (<ipython-input-4-dde01a80b6e8>, line 1)

In [5]:
L = list(range(10))


In [2]:
type(L[0])

int

In [3]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [4]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [2]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
import numpy as np

In [8]:
# :integer array
np.array([1, 4, 2, 5])

array([1, 4, 2, 5])

In [9]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [10]:
np.array([1, 2 , 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [11]:
np.array([range(i, i+3) for i in (2, 4, 6)])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [13]:
# create a length-10 integer array filled with zeros
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
import numpy as np
np.random.normal (0, 1 (3, 3))

TypeError: 'int' object is not callable