In [3]:
import numpy
numpy.version.version


'1.15.4'

In [3]:
import numpy
numpy:version.version
    

NameError: name 'version' is not defined

In [4]:
import numpy as np


In [6]:
np?


In [2]:
result = 0
for i in range(100):
    result += i


In [4]:
for i in range(5)
print(i)

SyntaxError: invalid syntax (<ipython-input-4-dde01a80b6e8>, line 1)

In [5]:
L = list(range(10))


In [2]:
type(L[0])

int

In [3]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [4]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [2]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
import numpy as np

In [8]:
# :integer array
np.array([1, 4, 2, 5])

array([1, 4, 2, 5])

In [9]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [10]:
np.array([1, 2 , 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [11]:
np.array([range(i, i+3) for i in (2, 4, 6)])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [13]:
# create a length-10 integer array filled with zeros
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
# create a 3X5 floating point array filled with 1s
np.ones ((3,5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# create a 3X5 array filled with 3.14
np.full ((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [17]:
np.arange (0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
import numpy as np
np.linspace(0, 1, 5, dtype = int)

array([0, 0, 0, 0, 1])

In [8]:
np.range(0, 1, 5)

AttributeError: module 'numpy' has no attribute 'range'

In [11]:
# create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3,3))

array([[0.8373602 , 0.01561337, 0.93182855],
       [0.73199468, 0.89405578, 0.11932332],
       [0.84288974, 0.06063273, 0.36622491]])

In [15]:
# create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1

np.random.normal (0, 1 (3, 3))

TypeError: 'int' object is not callable

In [16]:
np.random.randint(0, 10, (3,3))

array([[3, 2, 1],
       [6, 5, 7],
       [0, 7, 7]])

In [22]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.empty (3)

array([1., 1., 1.])

In [30]:
np.bool_?
