In [1]:
import numpy as np

In [2]:
L = np.random.random (100)
sum (L)

45.135436879482114

In [3]:
np.sum (L)

45.13543687948209

In [4]:
big_array = np.random.rand (1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

89.7 ms ± 3.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.15 ms ± 87.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
min(big_array), max(big_array)

(5.260645917770645e-07, 0.9999993865654987)

In [6]:
np.min (big_array), np.max (big_array)

(5.260645917770645e-07, 0.9999993865654987)

In [7]:
%timeit min (big_array)
%timeit np.min (big_array)

59.8 ms ± 616 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
447 µs ± 4.01 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
print (big_array.min(), big_array.max(), big_array.sum())

5.260645917770645e-07 0.9999993865654987 500208.4165515369


In [9]:
M = np.random.random ((3, 4))
print (M)

[[0.0779084  0.53025777 0.98192609 0.92292068]
 [0.36939508 0.46273834 0.77404432 0.49970678]
 [0.69486318 0.93769996 0.0063668  0.93941176]]


In [10]:
M.sum ()

7.197239159748367

In [11]:
M.min (axis = 0)

array([0.0779084 , 0.46273834, 0.0063668 , 0.49970678])

In [12]:
M.max (axis =1)

array([0.98192609, 0.77404432, 0.93941176])

In [13]:
import os 
import pandas as pd 
os.chdir("c:Desktop")
MLincs = pd.read_csv("dataset.csv")

FileNotFoundError: File b'dataset.csv' does not exist

In [ ]:
MLincs.columns

In [ ]:
!head -4 data/president_heights.csv

order,name,height(cm)
1,George washington,189
2, John Admas, 170
3, Thomas Jefferson, 189

In [15]:
import pandas as pd
data = pd.read_csv('data/president_heights.csv')
heights = np.array(data['height(cm)'])
print(heights)

FileNotFoundError: File b'data/president_heights.csv' does not exist

In [ ]:
import pandas as pd
data = pd.read_csv('data/president_heights.csv')
heights = np.array(data['height(cm)'])
print(heights)

In [ ]:
print("Mean height: ", heights.mean())
print("Standard deviation:", heights.std())
print("Minimum height: ", heights.min())
print("Maximum height: ", heights.max())

In [ ]:
import os
os.path.abspath(os.path.curdir)


In [16]:
%pwd

'C:\\Users\\Mannawar Hussain\\Desktop'

In [17]:
!head -4 data/president_heights.csv

'head' is not recognized as an internal or external command,
operable program or batch file.


In [21]:
import pandas as pd
data = pd.read_csv('C:\\Users\\Mannawar Hussain\\Desktop\\president_heights.csv')
heights = np.array(data['height(cm)'])
print(heights)

FileNotFoundError: File b'C:\\Users\\Mannawar Hussain\\Desktop\\president_heights.csv' does not exist